services:
  haproxy:
    image: haproxy:lts-alpine
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:8080"
    networks:
      - playground-network
    depends_on:
      - app1
      - app2
    links:
      - app1
      - app2

  app1:
    image: nginx:alpine
    container_name: app1
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      playground-network:
        ipv4_address: "10.0.0.21"

  app2:
    image: nginx:alpine
    container_name: app2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      playground-network:
        ipv4_address: "10.0.0.22"

networks:
  playground-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1