version: '3.7'
services:
  postgres-master:
    image: postgres:16
    container_name: postgres-master
    environment:
      POSTGRES_USER: your_master_user
      POSTGRES_PASSWORD: your_master_password
    ports:
      - "5432:5432"
    volumes:
      - ./master-data:/var/lib/postgresql/data
    networks:
      - playground-network

  postgres-slave:
    image: postgres:16
    container_name: postgres-slave
    environment:
      POSTGRES_USER: your_slave_user
      POSTGRES_PASSWORD: your_slave_password
      POSTGRES_MASTER_USER: your_master_user
      POSTGRES_MASTER_PASSWORD: your_master_password
      POSTGRES_MASTER_SERVICE: postgres-master
    depends_on:
      - postgres-master
    volumes:
      - ./slave-data:/var/lib/postgresql/data
    networks:
      - playground-network

networks:
  playground-network:
